### ISSUE TITLE
Build Failure 

### ISSUE THREAD

**Issue by waseemhehe** [abdallahmehiz/mpvKt#5]
Build file 'D:\mpv\mpvKt-main\app\build.gradle.kts' line: 161

Process 'command 'git'' finished with non-zero exit value 128

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.process.internal.ExecException: Process 'command 'git'' finished with non-zero exit value 128
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:442)
	at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:38)
	at org.gradle.process.internal.DefaultExecActionFactory.exec(DefaultExecActionFactory.java:202)
	at org.gradle.kotlin.dsl.support.DefaultKotlinScript.exec(DefaultKotlinScript.kt:125)
	at Build_gradle.runCommand(build.gradle.kts:161)
	at Build_gradle.getCommitSha(build.gradle.kts:158)
	at Build_gradle$1$1.invoke(build.gradle.kts:40)
	at Build_gradle$1$1.invoke(build.gradle.kts:21)
	
	
	on this 
	
	fun runCommand(command: String): String {
  val stdOut = ByteArrayOutputStream()
  exec {
    commandLine = command.split(' ')
    standardOutput = stdOut
  }
  return String(stdOut.toByteArray()).trim()
}

**Comment by abdallahmehiz** [comment]
you gotta add the cloned repo to your git safe directories

**Comment by waseemhehe** [comment]
yes i did that thanks!!, but this is in compose do u know where i can get xml mpv android , main mpv-android is not running because of native code

**Comment by abdallahmehiz** [comment]
I guess you can take a look at something like [Aniyomi](https://github.com/aniyomiorg/aniyomi) since the player for that uses mpv-android and is a mix of Views(XML) and Compose.

**Comment by abdallahmehiz** [comment]
There is Also [Anivu](https://github.com/SkyD666/AniVu)

**Comment by waseemhehe** [comment]
thanks brother
