### ISSUE TITLE
Subtitle customization options cause crash

### ISSUE THREAD

**Issue by 100pangci** [abdallahmehiz/mpvKt#99]
**Describe the bug**
When I want to customize the subtitle format, the program crashes

**To Reproduce**
I opened the app and played a video. I wanted to add subtitles to the video. After adding the subtitles, I wanted to customize the subtitle format. After clicking the subtitle format, the app crashed after two or three seconds.

**Expected behavior**
I expect it will bring up the subtitle custom formatting tool

**Actual behavior**
I clicked the Customize button and the app crashed.

**Crash logs**
```
      App version: 0.1.6 (ac95c8d)
Android version: 14 (34)
Device brand: Redmi
Device manufacturer: Xiaomi
Device model: Redmi K60 Pro (socrates)
MPV version: v0.38.0-743-gad7976c33e
ffmpeg version: 0b6d7cd9d9
libplacebo version: v7.349.0 (v7.349.0-9-gefb89342)
      
      Exception:
      java.io.EOFException: Reached EOF, file size=18315964
	at com.yubyf.truetypeparser.FontStreamReader.readTo(SourceFile:48)
	at com.yubyf.truetypeparser.TTFFile.readTablesOrderByOffset(SourceFile:159)
	at live.mehiz.mpvkt.ui.player.controls.components.panels.SubtitleSettingsTypographyCardKt$SubtitleSettingsTypographyCard$1$1.invokeSuspend(SourceFile:192)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at androidx.core.app.ActivityRecreator$1.run(SourceFile:15)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:92)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@8e9bff8, androidx.compose.runtime.BroadcastFrameClock@5d47cd1, StandaloneCoroutine{Cancelling}@4270336, AndroidUiDispatcher@95b0237]

      
      Logcat:
      --------- beginning of main
09-23 18:53:29.752 17515 17747 I CCodecConfig: query failed after returning 18 values (BAD_INDEX)
09-23 18:53:29.752 17515 17748 D CCodecBufferChannel: [c2.qti.hevc.decoder#572] flushed work; ignored.
09-23 18:53:29.752 17515 17748 D CCodecBufferChannel: [c2.qti.hevc.decoder#572] Discard frames from previous generation.
09-23 18:53:29.752 17515 17748 D CCodecBufferChannel: [c2.qti.hevc.decoder#572] flushed work; ignored.
09-23 18:53:29.752 17515 17748 D CCodecBufferChannel: [c2.qti.hevc.decoder#572] Discard frames from previous generation.
09-23 18:53:29.753 17515 17747 W Codec2Client: query -- param skipped: index = 1342179345.
09-23 18:53:29.753 17515 17747 W Codec2Client: query -- param skipped: index = 2415921170.
09-23 18:53:29.753 17515 17747 W Codec2Client: query -- param skipped: index = 1610614798.
09-23 18:53:29.755 17515 17747 I CCodecConfig: query failed after returning 18 values (BAD_INDEX)
09-23 18:53:29.755 17515 17747 W Codec2Client: query -- param skipped: index = 1342179345.
09-23 18:53:29.755 17515 17747 W Codec2Client: query -- param skipped: index = 2415921170.
09-23 18:53:29.755 17515 17747 W Codec2Client: query -- param skipped: index = 1610614798.
09-23 18:53:29.755 17515 17740 V mpv     : event: seek
09-23 18:53:29.767 17515 17752 D CCodecBufferChannel: [c2.qti.hevc.decoder#572] Ignoring stale input buffer done callback: last flush index = 9, frameIndex = 9
09-23 18:53:29.873 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:29.883 17515 17740 V mpv     : event: playback-restart
09-23 18:53:29.884 17515 17740 V mpv     : [cplayer:warn] Audio device underrun detected.
09-23 18:53:29.895 17515 17761 W AidlConversionCppNdk: aidl2legacy_AudioChannelLayout_audio_channel_mask_t: no legacy output audio_channel_mask_t found for AudioChannelLayout{layoutMask: 16}
09-23 18:53:29.996 17515 17524 W ive.mehiz.mpvkt: Cleared Reference was only reachable from finalizer (only reported once)
09-23 18:53:30.015 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.045 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.086 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.128 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.169 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.211 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.253 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.295 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.336 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.378 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.420 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.461 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.503 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.545 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.586 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.628 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.670 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.712 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.753 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.795 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.837 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.878 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.920 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:30.962 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.004 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.045 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.087 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.129 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.140 17515 17515 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
09-23 18:53:31.140 17515 17515 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
09-23 18:53:31.170 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.212 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.254 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.296 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.337 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.379 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.421 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.462 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.505 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.546 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.587 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.629 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.671 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.713 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.754 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.796 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.839 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.879 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.921 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:31.963 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:32.005 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:32.046 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:32.088 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:32.130 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:32.171 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:32.213 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:32.255 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:32.297 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:32.338 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:32.380 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:32.422 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:32.463 17515 17744 W qdgralloc: getInterlacedFlag: getMetaData returned 3, defaulting to interlaced_flag = 0
09-23 18:53:32.502 17515 17764 D mpvKt   : Saving playback state
09-23 18:53:33.062 17515 17515 D VRI[PlayerActivity]: visibilityChanged oldVisibility=true newVisibility=false
09-23 18:53:33.076 17515 17515 W mpv     : detaching surface
09-23 18:53:33.081 17515 17747 I CCodecConfig: query failed after returning 18 values (BAD_INDEX)
09-23 18:53:33.081 17515 17748 D CCodecBufferChannel: [c2.qti.hevc.decoder#572] flushed work; ignored.
09-23 18:53:33.081 17515 17748 D CCodecBufferChannel: [c2.qti.hevc.decoder#572] Discard frames from previous generation.
09-23 18:53:33.081 17515 17748 D CCodecBufferChannel: [c2.qti.hevc.decoder#572] flushed work; ignored.
09-23 18:53:33.081 17515 17748 D CCodecBufferChannel: [c2.qti.hevc.decoder#572] Discard frames from previous generation.
09-23 18:53:33.081 17515 17747 W Codec2Client: query -- param skipped: index = 1342179345.
09-23 18:53:33.081 17515 17747 W Codec2Client: query -- param skipped: index = 2415921170.
09-23 18:53:33.081 17515 17747 W Codec2Client: query -- param skipped: index = 1610614798.
09-23 18:53:33.081 17515 17747 D CCodecBufferChannel: [c2.qti.hevc.decoder#572] MediaCodec discarded an unknown buffer
09-23 18:53:33.081 17515 17747 D CCodecBufferChannel: [c2.qti.hevc.decoder#572] MediaCodec discarded an unknown buffer
09-23 18:53:33.081 17515 17747 D CCodecBufferChannel: [c2.qti.hevc.decoder#572] MediaCodec discarded an unknown buffer
09-23 18:53:33.081 17515 17747 D CCodecBufferChannel: [c2.qti.hevc.decoder#572] MediaCodec discarded an unknown buffer
09-23 18:53:33.092 17515 17747 D SurfaceUtils: disconnecting from surface 0xb400007a2e462090, reason disconnectFromSurface
09-23 18:53:33.094 17515 17740 V mpv     : event: video-reconfig
09-23 18:53:33.104 17515 17789 I hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
09-23 18:53:33.107 17515 17740 V mpv     : event: video-reconfig
09-23 18:53:33.109 17515 17740 V mpv     : event: video-reconfig
09-23 18:53:33.112 17515 17740 V mpv     : [ffmpeg/video:error] hevc_mediacodec: Both surface and native_window are NULL
09-23 18:53:33.115 17515 17793 D CCodec  : allocate(c2.qti.hevc.decoder)
09-23 18:53:33.119 17515 17793 I CCodec  : setting up 'default' as default (vendor) store
09-23 18:53:33.123 17515 17793 I CCodec  : Created component [c2.qti.hevc.decoder]
09-23 18:53:33.123 17515 17793 D CCodecConfig: read media type: video/hevc
09-23 18:53:33.125 17515 17793 D ReflectedParamUpdater: ignored struct field vendor.output.configs.portConfigs
09-23 18:53:33.129 17515 17793 D ReflectedParamUpdater: ignored struct field vendor.input.configs.portConfigs
09-23 18:53:33.130 17515 17793 D ReflectedParamUpdater: extent() != 1 for single value type: vendor.qti-ext-transcode-info-stats.stats_info
09-23 18:53:33.134 17515 17793 D ReflectedParamUpdater: extent() != 1 for single value type: vendor.qti-ext-vpp-extradata.extradata-types
09-23 18:53:33.134 17515 17793 D ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.pool-ids.values
09-23 18:53:33.138 17515 17793 D ReflectedParamUpdater: extent() != 1 for single value type: output.subscribed-indices.values
09-23 18:53:33.138 17515 17793 D CCodecConfig: ignoring local param raw.size (0xd2001800) as it is already supported
09-23 18:53:33.139 17515 17793 D CCodecConfig: ignoring local param default.color (0x5200180b) as it is already supported
09-23 18:53:33.139 17515 17793 D CCodecConfig: ignoring local param raw.hdr-static-info (0xd200180a) as it is already supported
09-23 18:53:33.140 17515 17793 I CCodecConfig: query failed after returning 18 values (BAD_INDEX)
09-23 18:53:33.140 17515 17793 D CCodecConfig: c2 config diff is Dict {
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::i32 algo.priority.value = -1
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::float algo.rate.value = 30
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::u32 algo.secure-mode.value = 0
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::float coded.frame-rate.value = 30
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::u32 coded.pl.level = 0
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::u32 coded.pl.profile = 24576
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::u32 coded.vui.color.matrix = 255
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::u32 coded.vui.color.primaries = 0
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::u32 coded.vui.color.range = 0
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::u32 coded.vui.color.transfer = 255
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::u32 default.color.matrix = 0
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::u32 default.color.primaries = 0
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::u32 default.color.range = 0
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::u32 default.color.transfer = 0
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::u32 input.buffers.max-size.value = 8847360
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::u32 input.delay.value = 0
09-23 18:53:33.140 17515 17793 D CCodecConfig:   string input.media-type.value = "video/hevc"
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::u32 output.delay.value = 12
09-23 18:53:33.140 17515 17793 D CCodecConfig:   Buffer output.hdr10-plus-info.value = {
09-23 18:53:33.140 17515 17793 D CCodecConfig:   }
09-23 18:53:33.140 17515 17793 D CCodecConfig:   string output.media-type.value = "video/raw"
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::u32 raw.color.matrix = 0
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::u32 raw.color.primaries = 0
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::u32 raw.color.range = 0
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::u32 raw.color.transfer = 0
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::float raw.hdr-static-info.mastering.blue.x = 0
09-23 18:53:33.140 17515 17793 D CCodecConfig:   c2::float raw.hdr-static-info.mastering.blue.y = 0
09-23 18:53:33.141 17515 17793 W ColorUtils: expected specified color aspects (0:0:0:0)
09-23 18:53:33.144 17515 17793 D CCodec  : [c2.qti.hevc.decoder] buffers are bound to CCodec for this session
09-23 18:53:33.145 17515 17793 D CCodec  : Client requested ByteBuffer mode decoder w/o color format set: using default semi-planar color format
09-23 18:53:33.145 17515 17793 D CCodecConfig: no c2 equivalents for flags
09-23 18:53:33.146 17515 17793 D CCodecConfig: c2 config diff is   c2::u32 raw.pixel-format.value = 2141391876
09-23 18:53:33.146 17515 17793 D CCodecConfig:   c2::u32 raw.size.height = 1080
09-23 18:53:33.146 17515 17793 D CCodecConfig:   c2::u32 raw.size.width = 1920
09-23 18:53:33.146 17515 17793 W ColorUtils: expected specified color aspects (0:0:0:0)
09-23 18:53:33.147 17515 17793 W Codec2Client: query -- param skipped: index = 1107298332.
09-23 18:53:33.147 17515 17793 D CCodec  : encoding statistics level = 0
09-23 18:53:33.147 17515 17793 D CCodec  : setup formats input: AMessage(what = 0x00000000) = {
09-23 18:53:33.147 17515 17793 D CCodec  :   int32_t feature-secure-playback = 0
09-23 18:53:33.147 17515 17793 D CCodec  :   int32_t frame-rate = 30
09-23 18:53:33.147 17515 17793 D CCodec  :   int32_t height = 1080
09-23 18:53:33.147 17515 17793 D CCodec  :   int32_t max-input-size = 8847360
09-23 18:53:33.147 17515 17793 D CCodec  :   string mime = "video/hevc"
09-23 18:53:33.147 17515 17793 D CCodec  :   int32_t priority = 1
09-23 18:53:33.147 17515 17793 D CCodec  :   int32_t profile = 1
09-23 18:53:33.147 17515 17793 D CCodec  :   int32_t width = 1920
09-23 18:53:33.147 17515 17793 D CCodec  :   Rect crop(0, 0, 1919, 1079)
09-23 18:53:33.147 17515 17793 D CCodec  : }
09-23 18:53:33.147 17515 17793 D CCodec  : setup formats output: AMessage(what = 0x00000000) = {
09-23 18:53:33.147 17515 17793 D CCodec  :   int32_t android._color-format = 2141391876
09-23 18:53:33.147 17515 17793 D CCodec  :   int32_t android._video-scaling = 1
09-23 18:53:33.147 17515 17793 D CCodec  :   int32_t android._dataspace = 0
09-23 18:53:33.147 17515 17793 D CCodec  :   int32_t color-standard = 0
09-23 18:53:33.147 17515 17793 D CCodec  :   int32_t color-range = 0
09-23 18:53:33.147 17515 17793 D CCodec  :   int32_t color-transfer = 0
09-23 18:53:33.147 17515 17793 D CCodec  :   int32_t sar-height = 1
09-23 18:53:33.147 17515 17793 D CCodec  :   int32_t rotation-degrees = 0
09-23 18:53:33.147 17515 17793 D CCodec  :   Buffer hdr-static-info = {
09-23 18:53:33.147 17515 17793 D CCodec  :     00000000:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
09-23 18:53:33.147 17515 17793 D CCodec  :     00000010:  00 00 00 00 00 00 00 00  00                       .........
09-23 18:53:33.147 17515 17793 D CCodec  :   }
09-23 18:53:33.147 17515 17793 D CCodec  :   int32_t sar-width = 1
09-23 18:53:33.147 17515 17793 D CCodec  :   Rect crop(0, 0, 1919, 1079)
09-23 18:53:33.147 17515 17793 D CCodec  :   int32_t width = 1920
09-23 18:53:33.147 17515 17793 D CCodec  :   int32_t feature-secure-playback = 0
09-23 18:53:33.147 17515 17793 D CCodec  :   int32_t frame-rate = 30
09-23 18:53:33.147 17515 17793 D CCodec  :   Buffer hdr10-plus-info = {
09-23 18:53:33.147 
```
 
**Screenshots**
![Screenshot_20240923-185549_mpvKt.png](https://github.com/user-attachments/assets/489d39b3-8626-4bf1-8c53-c2c3ee7de5b0)
![Screenshot_20240923-185610_mpvKt.png](https://github.com/user-attachments/assets/5d894382-69b7-462e-9d35-e3b6f70ccb96)
![Screenshot_20240923-185620_mpvKt.png](https://github.com/user-attachments/assets/396268e1-cec5-4df8-a464-24bf03c4beeb)
Displays briefly before crashing
![Screenshot_20240923-185642_mpvKt.png](https://github.com/user-attachments/assets/d173d541-a05c-4705-9acd-557c587696f3)
![Screenshot_20240923-191553_mpvKt.png](https://github.com/user-attachments/assets/c7103425-44af-4f2e-8133-12be4a2d9797)

**Additional info (please complete the following information):**
 - Device: [Redmi K60 Pro]
 - Android version: [14]
 - App Version: [0.1.6]

**Additional context**
I am using the Chinese environment and have just added a lot of font packages to the font directory (There are 429 font files there,Because I want the ssa subtitles to follow the internal font settings)

**Comment by abdallahmehiz** [comment]
You probably have a corrupt font file somewhere...
